#
# Makefile for the mc13783 adc drivers.
#

obj-$(CONFIG_MXC_MC13783_ADC) += mc13783_adc-mod.o
obj-$(CONFIG_MXC_MC13783_AUDIO) += mc13783_audio-mod.o
obj-$(CONFIG_MXC_MC13783_RTC) += mc13783_rtc-mod.o
obj-$(CONFIG_MXC_MC13783_LIGHT) += mc13783_light-mod.o
obj-$(CONFIG_MXC_MC13783_BATTERY) += mc13783_battery-mod.o
obj-$(CONFIG_MXC_MC13783_CONNECTIVITY) += mc13783_connectivity-mod.o
obj-$(CONFIG_MXC_MC13783_POWER) += mc13783_power-mod.o
mc13783_adc-mod-objs := mc13783_adc.o
mc13783_audio-mod-objs := mc13783_audio.o
mc13783_rtc-mod-objs := mc13783_rtc.o
mc13783_light-mod-objs := mc13783_light.o
mc13783_battery-mod-objs := mc13783_battery.o
mc13783_connectivity-mod-objs := mc13783_connectivity.o
mc13783_power-mod-objs := mc13783_power.o
