# Copyright (C) 2004-2006 Motorola, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as 
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  
# 02111-1307, USA
#
# Motorola 2006-Nov-01 - Support LJ7.1 Reference Design
# Motorola 2006-Oct-06 - Update File
# Motorola 2006-Jun-19 - Fix montavista upmerge conditionals
# Motorola 2006-May-13 - Addition of ZEUS support
# Motorola 2005-Dec-06 - Addition of BUTE support
# Motorola 2005-Mar-25 - Addition of SCM-A11 support
# Motorola 2004-Dec-17 - Initial Creation

obj-y       := core/ module/

fastdep:
