#!/bin/sh
#
# wlanext --- WLAN driver common initialization script


ethx="eth0"
usage="\nUsage:\nwlanext [-i <interface>]\n\nExample 1: 
      wlanext 2: wlanext -i eth1\n"

while [ $# -ge 1 ]; do
            case $1 in
            -i)    shift; ethx=$1;;
            -h)    echo -e 1>&2 $usage; exit;;
             *)    echo -e 1>&2 "\nInvalid argument $1"; echo -e 1>&2 $usage; exit;;
            esac
            shift
done

#
# Check for Local script
#
scriptPath=/mnt/msc_int0/wlan_driver/
scriptName=$scriptPath"wlanext"
if [ -f "$scriptName" ]; then
    sh $scriptName
else
    
    #echo ">>> Moving LED GPIO to GPIO3 <<<"
    iwpriv $ethx ledgpio 1 16 2 16 3 16 
     
    #echo ">>> setting WLAN_HOST_WAKEB as GPIO by FW to wakeup Host <<<"
    iwpriv $ethx hscfg 0xF 1 15  
        
    #echo ">>> setting beacon average weighting factor to 3 <<<"
    iwpriv $ethx setbcnavg 3

    #echo ">>> setting tx retry count to 9 <<<"
    iwconfig $ethx retry 9

    #echo ">>> setting transmit power to 13 (not used with power adaptation enabled - cmd removed)<<<"
    #iwconfig $ethx txpower 13

    #echo ">>> disable auto re-association <<<"
    iwpriv $ethx reasso-off

    #echo ">>> enable wmm <<<"
    iwpriv $ethx wmm 1

    #echo ">>> Set QoSinfo <<<"
    iwpriv $ethx wmm_qosinfo 0xF

    #echo ">>> disable Null packets <<<"
    iwpriv $ethx psnullinterval -1


    #
    #    configure 88W8686 3 wire, dual antenna BCA mode
    #
    #echo
    #echo ">>> configure 3 wire, dual antenna BCA mode <<<"
    #  BCA WLAN modes:
    #  [25] - 8686: 0 = only BT TX gets grants, 1 = BT dir info ignored
    #  [15] - WLAN RX/TX request: 0 = are used, 1 = are blocked
    #  [12] - BCA: 0 = 2w, 1 = 3/4w
    #  [11] - Antenna: 0 = dual, 1 = single  
    #  [ 3] - WLAN signal indication: 0 = RX MAC, 1 = CCA
    wlanconfig $ethx wrmac 0xa5f0 0xA227101C
    #
    #  BCA mode configuration:
    #  [15..12] - BCA decision table for single antenna
    #  [ 9]     - WLAN inputs: 0 = edge, 1 = level
    #  [ 7...6] - WLAN RX prio: 00 = low, 10 = high, x1 = use 0xa598/0xa59c
    #  [ 5]     - WLAN RX frame destination: 0 = all, 1 = unicasts
    #  [ 3]     - BCA allowed to stop WLAN TX: 0 = no, 1 = yes
    #  [ 2...1] - BT frequency: 00 = oob, 10 = in-band, x1 = use BT_FREQ
    #  [ 0]     - Enable BCA: 0 = disabled, 1 = enabled 
    wlanconfig $ethx wrmac 0xa5a0 0x0000D28D
    #
    #  BT switch control:
    #  [30..25] - antenna to WLAN RX [us] if no requests pending
    #  [24..19] - antenna to BT [us] if no requests pending 
    #  [18..17] - who gets antenna: 00 or 11 = as specified in [30:25] and [24:19],
    #                01 = given BT, 10 = given WLAN
    #  [16]     - T/R_ control: 0 = BCA, 1 = WLAN MAC
    #  [15]     - ANT_SEL_ control: 0 = BCA, 1 = WLAN MAC
    #  [11...8] - ANT_SEL_P, ANT_SEL_N, T/R_P, T/R_N when BT wins arbitration
    #  [ 7...4] - same for WLAN TX
    #  [ 3...0] - same for WLAN RX
    wlanconfig $ethx wrmac 0xa58c 0x00058214
    #
    #  BCA WLAN TX ok (dual antenna only):
    #  {WLAN prio, WLAN dir, BT prio, BT dir, freq} form pointer into this reg
    #wlanconfig $ethx wrmac 0xa5dc 0xffff0000
    #
    #  BCA BT TX ok (dual antenna only):
    #  {WLAN prio, WLAN dir, BT prio, BT dir, freq} form pointer into this reg
    #wlanconfig $ethx wrmac 0xa5e0 0x0000ffff
    #
    #  WLAN priority masks (default settings)
    #  WLAN TX
    wlanconfig $ethx wrmac 0xa590 0x40404044
    wlanconfig $ethx wrmac 0xa594 0x00111333
    #  WLAN RX
    wlanconfig $ethx wrmac 0xa598 0x00111111
    wlanconfig $ethx wrmac 0xa59c 0x00111333
    #  WLAN TX FW 
    wlanconfig $ethx wrmac 0xa5e4 0x00111111
    wlanconfig $ethx wrmac 0xa5e8 0x00111333
    #
    #  BCA Timer register (default settings)
    #  (set with 25ns resolution)
    #wlanconfig $ethx wrmac 0xa5ac 0x000000c8
    #wlanconfig $ethx wrmac 0xa5b0 0x00000320 
    #wlanconfig $ethx wrmac 0xa5a8 0x00000708
    #wlanconfig $ethx wrmac 0xa5a4 0x00000c80
    #wlanconfig $ethx wrmac 0xa5b4 0x00000c80
    #wlanconfig $ethx wrmac 0xa5b8 0x000052d0
    #wlanconfig $ethx wrmac 0xa5bc 0x00000258
    #wlanconfig $ethx wrmac 0xa5c0 0x00000ed8
    #
    # BCA timesharing settings
    wlanconfig $ethx bca-ts set 1 60 30
    wlanconfig $ethx bca-ts set 0 20 10
    #
    #
    #echo ">>> 3w BCA configured <<<"
    #echo

    #echo ">>> inactive timeout <<<"
    iwpriv $ethx inactivityto 20
    
    #echo ">>> enable power adaptation <<<"
    wlanconfig $ethx hostcmd /etc/hostcmd.conf pa_cfg_ext_set
    
    #echo ">>> clock settings to use external 32KHz clock<<<"
    wlanconfig $ethx sleepparams set 200 500 4000 2 2 4810

    
    #echo ">>> driver version <<<"
    iwpriv $ethx version

fi 

exit
