# Makefile - to build mmc/sd driver module and release it
#
# Copyright 2006 Motorola, Inc. 
#
# 
ifeq ($(PLATFORM),linuxjava)
include $(BOOTSTRAP)
.PHONY: api_build impl
api_build: $(PROPFILES)

impl:
endif
