#
# Makefile for the mc13783 core drivers.
#

obj-$(CONFIG_MXC_MC13783_LEGACY) += mc13783-core-mod.o
mc13783-core-mod-objs := mc13783_core.o mc13783_register.o mc13783_spi_inter.o mc13783_event.o mc13783_external.o
