
/* Generated by otg-states-h.awk
 *
 * Do not Edit thie file
 */
/*
 * Copyright 2005-2006 Motorola, Inc.
 *
 * Changelog:
 * Date               Author           Comment
 * -----------------------------------------------------------------------------
 * 12/12/2005         Motorola         Initial distribution
 * 10/18/2006         Motorola         Add Open Src Software language
 * 12/12/2006         Motorola         Changes for Open Src compliance.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

/*!
* @file otg/otg/otg-fw-df.h
* @brief OTG Firmware - Firmware for df
*
* This file defines the OTG State Machine tests.
*
* @ingroup OTGFW
*/


/*!
* @page OTGFW
* @section OTGFW - otg-fw-df.h
* This contains the input, output and timout definitions for the OTG state machine firmware
*/
extern char     otg_fw_name_df[];
extern int      otg_test_max_df;
extern struct otg_test otg_tests_df[];
extern struct otg_output otg_outputs_df[];

 /*
  * Copyright (c) 2004 Belcarra
  *
  */
 /*!
  * This is the default Firmware. It is included in the
  * compiled modules and supports the auto Traditional USB
  * mode. No user inputs are implemented.
  */

#define invalid_state                   0	 /*  State machine has been initialized. */

#define otg_disabled                    1	 /*  State machine has been initialized. */

#define terminator_state                2	 /*  terminator */
 /*
  * This is not an OTG State. It is used internally to mark the end of the
  * list of states and inputs.
  */

#define OTG_STATES_DF      3

extern struct otg_state otg_states_df[OTG_STATES_DF + 1];

extern char    *otg_get_state_name_df(int);

extern struct otg_firmware otg_firmware_df;
