obj-$(CONFIG_MXC_IPU) += mxc_ipu.o

mxc_ipu-objs := ipu_common.o ipu_sdc.o ipu_adc.o ipu_ic.o ipu_alloc.o ipu_csi.o ipu_lpmc.o

obj-$(CONFIG_MXC_IPU_PF)	+=   pf/
obj-$(CONFIG_MOT_FEAT_IPU_PP)	+=   pp/
