#
# Makefile for the SC55112 PMIC module drivers.
#

obj-$(CONFIG_MXC_PMIC_SC55112_CONNECTIVITY) += pmic_convity.o
pmic_convity-mod-objs := pmic_convity.o

obj-$(CONFIG_MXC_PMIC_SC55112_AUDIO) += pmic_audio.o
pmic_audio-mod-objs := pmic_audio.o

obj-$(CONFIG_MXC_PMIC_SC55112_ADC) += pmic_adc-mod.o
obj-$(CONFIG_MXC_PMIC_SC55112_LIGHT) += pmic_light-mod.o
obj-$(CONFIG_MXC_PMIC_SC55112_BATTERY) += pmic_battery-mod.o
obj-$(CONFIG_MXC_PMIC_SC55112_POWER) += pmic_power-mod.o
pmic_adc-mod-objs := pmic_adc.o
pmic_light-mod-objs := pmic_light.o
pmic_battery-mod-objs := pmic_battery.o
pmic_power-mod-objs := pmic_power.o
